services:
  # ollama:
  #   volumes:
  #     - ollama:/root/.ollama
  #   container_name: ollama
  #   pull_policy: always
  #   tty: true
  #   restart: unless-stopped
  #   image: ollama/ollama:${OLLAMA_DOCKER_TAG}

  nginx:
    image: 'nginx:alpine'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data/nginx/custom:/etc/nginx/conf.d
      - ./ssl_cert:/etc/ssl/custom
      - ./update_webui_host.sh:/update_webui_host.sh
    depends_on:
      - open-webui
    extra_hosts:
      - host.docker.internal:host-gateway

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG}
    container_name: open-webui
    volumes:
      - open-webui-data:/app/backend/data
    # Original ports configuration:
    # ports:
    #   - ${OPEN_WEBUI_PORT}:8080
    # Changed from publishing port to just exposing it
    expose:
      - 8080
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - KAGA_API_KEY=${KAGA_API_KEY}
      - DEFAULT_CONTEXT_LENGTH=${DEFAULT_CONTEXT_LENGTH}
      - CLAUDE_CONTEXT_LENGTH=${CLAUDE_CONTEXT_LENGTH}
      - PERPLEXITY_CONTEXT_LENGTH=${PERPLEXITY_CONTEXT_LENGTH}
      - OPENAI_CONTEXT_LENGTH=${OPENAI_CONTEXT_LENGTH}
      - TTS_ENGINE=${TTS_ENGINE}
      - TTS_VOICE=${TTS_VOICE}
      - STT_ENGINE=${STT_ENGINE}
      - SCARF_NO_ANALYTICS=${SCARF_NO_ANALYTICS}
      - DO_NOT_TRACK=${DO_NOT_TRACK}
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  # ollama: {}
  open-webui-data:
    name: open-webui-fw_open-webui
